site_name: McKnowledge Base
site_url: https://mpmc-git.github.io/McGitNotes/
site_description: A collection of formulas, SOQL queries, and technical notes.

# Enable Markdown extensions
markdown_extensions:
  - admonition # For notes, warnings, etc.
  - pymdownx.details # For collapsible content
  - pymdownx.emoji # Emoji support
  - pymdownx.highlight # Enhanced syntax highlighting
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.superfences # Advanced fenced code blocks
  - pymdownx.tabbed # For tabbed content

# Use the Material theme
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.insant # Instant navigation
    - search.suggest # Helpful search suggestions
    - content.tabs # Ability to create tabbed content (e.g., Excel vs. Sheets)
      # Removed navigation.sections so I could have drop-downs
      # Removed navigation.tabs due to issues with screen sizing
  palette:
    # 1. Dark Mode Palette
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # 2. Light Mode Palette
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7 # Icon for Sun/Light
        name: Switch to dark mode

# Define the navigation structure
nav:
  - Home: index.md # Formatted
  - URLs: urlz/earls.md # Formatted
  - Gaming-Related:
    - Minecraft: gaming/minecraft.md # Formatted
    - Via: gaming/via-cp.md # Copied from Original
  - Markup Languages:
    - HTML: markup/html.md # Formatted
    - Markdown: markup/markdown.md # Formatted
    - Markdown - Mkdocs: markup/mkdocs.md # Formatted
    - YAML: markup/yaml.md # Currently blank
  - Networking:
    - NMAP: networking/nmap.md # Formatted
    - Wireshark: networking/wireshark.md # Formatted
  - OS Specifics: 
    - Bash (Used in Linux): oses/bash-cp.md # Copied from Original
    - Linux: oses/linux.md # Formatted
    - Via (Used in Linux): oses/via.md # ORIGINAL
  - Points to Ponder:
    - From LinkedIn: pts2p/from-linkedin.md
    - Inspirationals:
      - General: pts2p/inspirationals.md # Formatted
      - Daily Philosophy: pts2p/subpts2p/365days/365-philosophy.md # Formatted
      - Daily Psychology: pts2p/subpts2p/365days/365-psychology.md # Formatted      
      - Inspiring Women: pts2p/subpts2p/365days/365-women.md # Formatted
  - Programming Languages: 
    - General: programming/general.md # Formatted
    - Apex: programming/apex.md # Formatted
    - GitHub: programming/github.md # Formatted
    - REST/Tooling API: programming/sfdc-rest-tool.md # ORIGINAL
  - Querying Languages: 
    - JQL/Jira: querying/jira.md # Formatted
    - Regex: querying/regex.md # Formatted
    - SOQL: querying/soql.md # ORIGINAL
    - SQL: querying/sql.md # Formatted
  - Salesforce:
    - Apex: programming/apex.md # Formatted
    - Apps / Extensions: salesforce/sfdc-apps-exts.md
    - Formulas: salesforce/sfdc-formulae.md
    - Free Tier: salesforce/sfdc-free-tier.md # Formatted
    - Rest/Tooling API: salesforce/sfdc-rest-tool-cp.md # Copied from Original
    - SOQL: salesforce/soql-cp.md # Copied from Original
    - Validation Rules: salesforce/sfdc-val-rulz.md # Formatted
  - Scripting Languages: 
    - Bash: scripting/bash.md # ORIGINAL
    - PowerShell: scripting/powershell.md # NEEDS TESTING AND FORMATTING
    - VBA: scripting/vba.md # Formatted
  - Spreadsheets: 
    - Excel / Sheets: spreadsheets/excel-lent.md # Formatted
    - Smartsheet: spreadsheets/smartsheet.md # Formatted
    - VBA: scripting/vba.md # Formatted
    - VLOOKUPS vs INDEX-MATCH: spreadsheets/subsheets/vlookup-vs-index-match.md # Formatted
