site_name: McKnowledge Base
site_url: https://MPMc-Git.github.io/knowledge-base/
site_description: A collection of formulas, SOQL queries, and technical notes.

# Use the Material theme
theme:
    name: material
    features:
        - navigation.tabs # Top-level navigation
        - search.suggest # Helpful search suggestions
        - content.tabs # Ability to create tabbed content (e.g., Excel vs. Sheets)
    palette:
        # Set the scheme to 'slate' to force Dark Mode
        - scheme: slate
            primary: blue
            accent: indigo
            toggle:
                icon: material/brightness-4 # Sets the default toggle icon to 'light mode'
                name: "Switch to light mode"

# Define the navigation structure
nav:
    - Home: index.md
    - Earls: urlz/index.md
    - Excel / Sheets / Smartsheet: spreadsheets/index.md
    - Gaming-Related: gaming/index.md
    - Linux Things: linux/index.md
    - Markup Languages: markup/index.md
    - Points to Ponder: pts2p/index.md
    - Programming Languages: programming/index.md
    - Querying Languages: querying/index.md
    - Salesforce: salesforce/index.md
    - Scripting Languages: scripting/index.md
