site_name: McKnowledge Base
site_url: https://mpmc-git.github.io/McGitNotes/
site_description: A collection of formulas, SOQL queries, and technical notes.

# Enable Markdown extensions
markdown_extensions:
  - admonition

# Use the Material theme
theme:
  name: material
  features:
    - navigation.tabs # Top-level navigation
    - search.suggest # Helpful search suggestions
    - content.tabs # Ability to create tabbed content (e.g., Excel vs. Sheets)
  palette:
    # 1. Dark Mode Palette
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # 2. Light Mode Palette
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7 # Icon for Sun/Light
        name: Switch to dark mode

# Define the navigation structure
nav:
  - Home: index.md # Formatted
  - URLs: urlz/earls.md # Formatted
  - Gaming-Related:
    - Minecraft: gaming/minecraft.md
    - Via: oses/via.md
  - Markup Languages:
    - HTML: markup/html.md
    - Mkdocs: markup/mkdocs.md
    - Markdown: markup/markdown.md
    - YAML: markup/yaml.md
  - OS Specifics: 
    - Bash (Used in Linux): scripting/bash.md
    - Linux: oses/linux.md
    - Via (Used in Linux): oses/via.md
  - Points to Ponder:
    - From LinkedIn: pts2p/from-linkedin.md
  - Programming Languages: 
    - Apex: programming/apex.md
    - GitHub: programming/github.md
    - REST/Tooling API: programming/sfdc-rest-tool.md
  - Querying Languages: 
    - JQL/Jira: programming/jira.md
    - Regex: querying/regex.md
    - SOQL: querying/soql.md
    - SQL: querying/sql.md
  - Salesforce:
    - Apex: programming/apex.md
    - Formulas: salesforce/sfdc-formulae.md
    - Rest/Tooling API: programming/sfdc-rest-tool.md
    - SOQL: querying/soql.md
    - Validation Rules: salesforce/sfdc-val-rulz.md
  - Scripting Languages: 
    - Bash: scripting/bash.md
    - PowerShell: scripting/powershell.md
    - VBA: scripting/vba.md
  - Spreadsheets: 
    - Excel / Sheets: spreadsheets/excel-lent.md
    - Smartsheet: spreadsheets/smartsheet.md
    - VBA: scripting/vba.md
