site_name: McKnowledge Base
site_url: https://mpmc-git.github.io/McGitNotes/
site_description: A collection of formulas, SOQL queries, and technical notes.

# Enable Markdown extensions
markdown_extensions:
  - admonition # For notes, warnings, etc.
  - attr_list # Allows setting attributes on the code block
  - meta
  - pymdownx.details # For collapsible content
  - pymdownx.emoji # Emoji support
  - pymdownx.escapeall # Escape special characters
  - pymdownx.highlight # Enhanced syntax highlighting - ISSUES ARE BEING HAD
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.superfences: # Advanced fenced code blocks - ISSUES ARE BEING HAD
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed # For tabbed content

# Plugins to enhance functionality
plugins:
  - search # Built-in search functionality
  - tags:
      case_sensitive: false
      enabled: true

# Use the Material theme
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.code.annotate # Code annotations
    - content.code.copy  # <--- This adds the copy button globally
    - content.code.linenums # Line numbers in code blocks
    - content.tabs # Ability to create tabbed content (e.g., Excel vs. Sheets)
    - content.tabs.link
    # Removed navigation.sections so I could have drop-downs
    # Removed navigation.tabs due to issues with screen sizing
    - navigation.indexes
    - navigation.insant # Instant navigation
    - search.highlight
    - search.share
    - search.suggest # Helpful search suggestions
  palette:
    # 1. Dark Mode Palette
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # 2. Light Mode Palette
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/brightness-7 # Icon for Sun/Light
        name: Switch to dark mode

# CSS
extra_css:
  - assets/stylesheets/extra.css

# Javascript
extra_javascript:
- https://unpkg.com/mermaid@10/dist/mermaid.min.js

# Define the navigation structure
nav:
# -> FIX THIS    - Bash (Used in Linux): oses/bash-cp.md # Copied from Original
# -> FIX THIS    - Via: gaming/via-cp.md # Copied from Original
# -> FIX THIS    - Rest/Tooling API: salesforce/sfdc-rest-tool-cp.md # Copied from Original
# -> FIX THIS    - SOQL: salesforce/soql-cp.md # Copied from Original
  - Start Here: index.md # Formatted
  - URLz: earls.md # Formatted
  - Business:
    - KPI vs KRI: business/kpi-vs-kri.md # Formatted
  - Gaming:
    - City of Heroes: gaming/coh.md # Formatted
    - Minecraft: gaming/minecraft.md # Formatted
  - Hardware:
    - Via (Keebmonkey): hardware/via.md # ORIGINAL
  - Linux: oses/linux.md # Formatted
  - Markup Languages:
    - HTML: markup/html.md # Formatted
    - Markdown: markup/markdown.md # Formatted
    - Markdown - Mkdocs: markup/mkdocs.md # Formatted
    - YAML: markup/yaml.md # Currently blank
  - Networking:
    - NMAP: networking/nmap.md # Formatted
    - Wireshark: networking/wireshark.md # Formatted
  - Points to Ponder:
    - Main: index-pts2p.md # Formatted
    - Daily P2P:
      - Daily Philosophy: pts2p/365days/365-philosophy.md # Formatted
      - Daily Psychology: pts2p/365days/365-psychology.md # Formatted
      - Forgotten Words: pts2p/365days/365-forgotten-words.md # Formatted
      - Inspiring Women: pts2p/365days/365-women.md # Formatted
  - Programming Languages: 
    - Main: index-pgram.md # Formatted
    - Apex: programming/apex.md # Formatted
    - GitHub: programming/github.md # Formatted
    - REST/Tooling API: programming/sfdc-rest-tool.md # ORIGINAL
  - Querying Languages: 
    - JQL/Jira: querying/jira.md # Formatted
    - Regex: querying/regex.md # Formatted
    - SOQL/Salesforce: querying/soql.md # ORIGINAL
    - SQL: querying/sql.md # Formatted
  - Salesforce:
    - Random Facts:
      - ID18: salesforce/subsfdc/salesforce-id18.md # Formatted
      - Order of Execution: salesforce/subsfdc/sfdc-ooe.md # Formatted
    - Apps / Extensions: salesforce/sfdc-apps-exts.md # NEEDS TESTING but Formatted
    - Formulas: salesforce/sfdc-formulae.md
    - Free Tier: salesforce/sfdc-free-tier.md # Formatted
    - Validation Rules: salesforce/sfdc-val-rulz.md # Formatted
  - Scripting Languages: 
    - Bash: scripting/bash.md # ORIGINAL
    - PowerShell: scripting/powershell.md # NEEDS TESTING AND FORMATTING
    - VBA: scripting/vba.md # Formatted
  - Spreadsheets: 
    - Excel / Sheets: spreadsheets/excel-lent.md # Formatted
    - Smartsheet: spreadsheets/smartsheet.md # Formatted
    - VLOOKUP vs INDEX-MATCH: spreadsheets/subsheets/vlookup-vs-index-match.md # Formatted
  - Timelines:
    - Historical: timelines/historical.md # Formatted
    - Philsophical/Religious: timelines/philosophical.md # Formatted
    - Scientific: timelines/scientific.md # Formatted
    - Technical: timelines/technical.md # Formatted
